blueprint:
  name: Simple Smart Heating
  description: "A simple smart room heating solution for home assistant.\n- Automatic switch off when windows are open\n- Away mode when you are away from home\n- Eco mode when nobody is in the room but you are at home\n- Comfort mode when someone is in the room and you are at home\n- Eco and Comfort temperatures for day and night"
  domain: automation
  source_url: https://github.com/easterapps/homeassistant-blueprints/blob/main/simple-smart-heating.yaml
  input:
    climate_entity:
      name: Climate Entity
      description: The Climate entity in the room
      selector:
        entity:
           domain: climate
    presence_at_home:
      name: Presence at home
      description: Indicates if someone is at home
      default:
      selector:
        entity:
          domain: [binary_sensor, input_boolean]
    presence_in_the_room:
      name: Presence in the room
      description: Indicates if someone is at home
      default:
      selector:
        entity:
          domain: [binary_sensor, input_boolean]
    away_mode_trigger_time:
      name: Away Trigger Time
      description: The time to wait before switching to Away mode.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    away_mode_temperature:
      name: Away Mode Temperature
      description: The temperature that is set when nobody is at home
      default: 16
      selector:
        number:
          min: 5
          max: 25
          unit_of_measurement: temperature
    eco_mode_day_temperature:
      name: Eco Day Mode Temperature
      description: The temperature during the day when someone is at home, but not in this room
      default: 18
      selector:
        number:
          min: 5
          max: 25
          unit_of_measurement: temperature
    eco_mode_night_temperature:
      name: Eco Night Mode Temperature
      description: The temperature during the night when someone is at home, but not in this room
      default: 17
      selector:
        number:
          min: 5
          max: 25
          unit_of_measurement: temperature
    comfort_mode_day_temperature:
      name: Comfort Day Mode Temperature
      description: The temperature during the day when someone is at home and in this room
      default: 18
      selector:
        number:
          min: 5
          max: 25
          unit_of_measurement: temperature
    comfort_mode_night_temperature:
      name: Comfort Night Mode Temperature
      description: The temperature during the night when someone is at home and in this room
      default: 17
      selector:
        number:
          min: 5
          max: 25
          unit_of_measurement: temperature
    window_contact:
      name: Window Contact
      description: Window of the room
      default:
      selector:
        entity:
          domain: [binary_sensor, input_boolean]
    window_open_trigger_time:
      name: Window Open Trigger Time
      description: The time to wait after window opened.
      default: 5
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds     
    window_closed_trigger_time:
      name: Window Closed Trigger Time
      description: The time to wait after window closed.
      default: 600
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds     
    day_start_time:
      name: Day Start Time
      description: Time when the day begins
      default: "06:00:00"
      selector:
        time:
    night_start_time:
      name: Night Start Time
      description: Time when the day begins
      default: "06:00:00"
      selector:
        time:
    
 
mode: restart
max_exceeded: silent
variables:
  climate_entity: !input climate_entity
  presence_at_home: !input presence_at_home
  presence_in_the_room: !input presence_in_the_room
  away_mode_trigger_time: !input away_mode_trigger_time
  away_mode_temperature: !input away_mode_temperature
  eco_mode_day_temperature: !input eco_mode_day_temperature
  eco_mode_night_temperature : !input eco_mode_night_temperature
  comfort_mode_day_temperature : !input comfort_mode_day_temperature
  comfort_mode_night_temperature: !input comfort_mode_night_temperature
  day_start_time: !input day_start_time
  night_start_time: !input night_start_time
  window_contact: !input window_contact
  window_closed_trigger_time: !input window_closed_trigger_time
  window_open_trigger_time: !input window_open_trigger_time

trigger:
  - platform: state
    entity_id: !input presence_at_home
  - platform: state
    entity_id: !input window_contact
    from: "off"
    to: "on"
    for: !input window_open_trigger_time
  - platform: state
    entity_id: !input window_contact
    to: "off"
    for: !input window_closed_trigger_time
    from: "on"
  - platform: state
    entity_id: !input presence_in_the_room
  - platform: time
    at: !input day_start_time
    alias: Day Start
  - platform: time
    at: !input night_start_time
    alias: Night Start
action:
  - if:
      - condition: state
        entity_id: !input window_contact
        state: "on"
    then:
      - service: climate.turn_off
        data: {}
        target:
          entity_id: !input climate_entity
    else:
      - choose:
          - conditions:
              - condition: state
                entity_id: !input presence_at_home
                state: "off"
                alias: Away Mode
                for: !input away_mode_trigger_time
            sequence:
              - service: climate.set_temperature
                data:
                  temperature: !input away_mode_temperature
                target:
                  entity_id: !input climate_entity
          - conditions:
              - condition: state
                entity_id: !input presence_at_home
                state: "on"
                alias: At Home
              - condition: state
                entity_id: !input presence_in_the_room
                state: "on"
                alias: In Room
            sequence:
              - choose:
                  - conditions:
                      - condition: time
                        after: !input day_start_time
                        before: !input night_start_time
                    sequence:
                      - service: climate.set_temperature
                        data:
                          temperature: !input comfort_mode_day_temperature
                          hvac_mode: heat
                        target:
                          entity_id: !input climate_entity
                  - conditions:
                      - condition: time
                        after: !input night_start_time
                        before: !input day_start_time
                    sequence:
                      - service: climate.set_temperature
                        data:
                          temperature: !input comfort_mode_night_temperature
                          hvac_mode: heat
                        target:
                          entity_id: !input climate_entity
          - conditions:
              - condition: state
                entity_id: !input presence_at_home
                state: "on"
              - condition: state
                entity_id: !input presence_in_the_room
                state: "off"
            sequence:
              - choose:
                  - conditions:
                      - condition: time
                        after: !input day_start_time
                        before: !input night_start_time
                    sequence:
                      - service: climate.set_temperature
                        data:
                          temperature: !input eco_mode_day_temperature
                          hvac_mode: heat
                        target:
                          entity_id: !input climate_entity
                  - conditions:
                      - condition: time
                        after: !input night_start_time
                        before: !input day_start_time
                    sequence:
                      - service: climate.set_temperature
                        data:
                          temperature: !input eco_mode_night_temperature
                          hvac_mode: heat
                        target:
                          entity_id: !input climate_entity
